// vuex_app/src/views/Home/Todos/Todos.vue
<template>
    <div class="todos">
        <todo
            v-for="(td, i) in todos"
            :key="i"
            :todo="td"
        />
    </div>
</template>

<script>
import Todo from './Todo/Todo'

export default {
    name: 'Todos',
    components:{
        todo: Todo
    },
    computed:{
        todos(){
            return this.$store.getters.todos.todos
        }
    }
}
</script>

<style>

</style>

// react-redux-type/src/App/views/Home/Todos/Todos.js
import React from 'react';
import Todo from './Todo/Todo'

const Todos = ({todos,deleteTodo,toggleDone}) => {
      
    return (
        <div className="todos">
            {todos && todos.map((todo, i)=>
                <Todo 
                    key={i} 
                    deleteTodo={deleteTodo} 
                    toggleDone={toggleDone}
                    todo={todo}/>
            )}
        </div>
    );
}

export default Todos;
