// vue_app/src/views/Home/Todos/Todos.vue
<template>
    <div class="todos">
        <todo
            v-for="(td, i) in todos"
            :key="i"
            :todo="td"
        />
    </div>
</template>

<script>
import Todo from './Todo/Todo'
import firebase from 'firebase'

export default {
    name: 'Todos',
    components:{
        todo: Todo
    },
    data(){
        return{
            todos:[]
        }
    },
    created(){
        const db = firebase.firestore().collection('todos')
        const id = firebase.auth().currentUser.uid
        db.doc(id).onSnapshot(snap=>{
            if(snap.exists){
                this.todos = snap.data().todos
            }
        })
    }
}
</script>

<style>

</style>

// react-hooks/src/App/views/Home/Todos/Todos.js
import React, {useState} from 'react';
import firebase from 'firebase';
import Todo from './Todo/Todo'

const Todos = () => {
    const [todos, setTodos] = useState([]);
    const userCollection = ()=>{
        const db = firebase.firestore().collection('todos')
        const id = firebase.auth().currentUser.uid
        
        return db.doc(id)
    }
    userCollection().onSnapshot(snap=>{
        if(snap.exists){
            setTodos(snap.data().todos)
        }
    })
    return (
        <div className="todos">
            {todos && todos.map(todo=><Todo todo={todo}/>)}
        </div>
    );
}

export default Todos;
