// vue_app/src/views/Home/Home.vue
<template>
    <main class="home">
        <a @click="logout" class="logout">Logout</a>
        <h1>TodoList</h1>
        <add-todo/>
        <todos/>
        <p class="error"></p>
    </main>
</template>

<script>
import AddTodo from './AddTodo/AddTodo'
import Todos from './Todos/Todos'
import firebase from 'firebase'

export default {
    name: 'Todos',
    components:{
        'add-todo': AddTodo,
        'todos': Todos
    },
    methods: {
        logout(){
            firebase.auth().signOut()
        }
    },
}
</script>

<style scoped>

</style>

// react-hooks/src/App/views/Home/Home.js
import React from 'react';
import firebase from 'firebase';
import AddTodo from './AddTodo/AddTodo';
import Todos from './Todos/Todos';

const Home = ({history}) => {
    if(!firebase.auth().currentUser){
        history.replace('/auth')
    }
    return (
        <main className="home">
            {/* <a class="logout">Logout</a> */}
            <h1>TodoList</h1>
            <AddTodo/>
            <Todos/>
            <p className="error"></p>
        </main>
    );
}

export default Home;
